(defun demo() 
 (setq fp (open "theString.txt" :direction :input)) 
(setq here (read fp "done")) 
(princ "processing") 
(princ here)
 (state0 here)
 )

(setq x' (x x))
(setq y' (y y))
(setq z' (z z))
(setq a' (a a))

(defun state0(list)
(COND ((null list) nil)
(defun state1(list)
(COND ((null list) T)
(defun state2(list)
(COND ((null list) nil)
(defun state3(list)
(COND ((null list) T)
